## 1.1 Matrices

In [4]:
arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
import numpy as np
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

## 1.2 1x1 and Random matrix

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [12]:
np.random.rand(3,3)

array([[0.56295782, 0.74013595, 0.60898124],
       [0.25787564, 0.71069095, 0.05815324],
       [0.50680715, 0.10844501, 0.91140401]])

In [14]:
torch.rand(3,3)

tensor([[0.8202, 0.5349, 0.9708],
        [0.9902, 0.6198, 0.9921],
        [0.4107, 0.9637, 0.4029]])

## 1.3 Seeds for Reproducibility 